# Generated by Django 3.0 on 2020-01-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_auto_20200113_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('choice', models.CharField(choices=[('N', 'Negative'), ('P', 'Positive'), ('I', 'PositiveIfNeeded')], max_length=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Date')),
            ],
        ),
    ]
